### ISSUE TITLE
添加feed URL时陷入死循环

### ISSUE THREAD

**Issue by Ti800** [steveluoxin/steveluoxin.github.io#1]
抱歉在这里反馈bug，我实在找不到你们的feedback渠道。

在连续添加feed URL时，会将当前添加的URL识别为上一个添加成功的feed，唯一解决办法是对上一个feed取消订阅，导致我陷入「要订阅新feed就要取消上一个」的死循环。

iOS15.1.1

**Comment by steveluoxin** [comment]
> 抱歉在这里反馈bug，我实在找不到你们的feedback渠道。
> 
> 在连续添加feed URL时，会将当前添加的URL识别为上一个添加成功的feed，唯一解决办法是对上一个feed取消订阅，导致我陷入「要订阅新feed就要取消上一个」的死循环。
> 
> iOS15.1.1


您好！

反馈通道：设置 - 更多 - 反馈建议

如果在「输入订阅网址」页面自动弹出：检测到剪切板网址，轻点**取消**按钮，并输入您需要的订阅网址即可。

![screenshot](https://user-images.githubusercontent.com/8499468/143793860-df772ac8-0aa4-4874-ada3-9c2ac35ce876.jpeg)

**Comment by Ti800** [comment]
![640D2FAF-21EF-46D6-926B-CE2C2E5E78ED](https://user-images.githubusercontent.com/53323379/143805586-26d5f0c8-2887-48d9-9c5f-c535da3daaa8.png)

https://user-images.githubusercontent.com/53323379/143805604-140b0af7-e656-4291-b8ea-98706323b8b7.MP4

我准备添加一个新feed，但跳出来一个其他已经订阅的feed。
复现步骤：
1.Safari打开连接https://rsshub.app/adnmb/20
2.copy地址
3.打开pindoo添加地址

**Comment by steveluoxin** [comment]
> 抱歉在这里反馈bug，我实在找不到你们的feedback渠道。
> 
> 在连续添加feed URL时，会将当前添加的URL识别为上一个添加成功的feed，唯一解决办法是对上一个feed取消订阅，导致我陷入「要订阅新feed就要取消上一个」的死循环。
> 
> iOS15.1.1

您好！感谢指出，这是 bug，将在后续的更新中修复。

反馈邮箱：pindurss@outlook.com

**Comment by steveluoxin** [comment]
> 抱歉在这里反馈bug，我实在找不到你们的feedback渠道。
> 
> 在连续添加feed URL时，会将当前添加的URL识别为上一个添加成功的feed，唯一解决办法是对上一个feed取消订阅，导致我陷入「要订阅新feed就要取消上一个」的死循环。
> 
> iOS15.1.1

您好！感谢指出，这是 bug，将在后续的更新中修复。

反馈邮箱：pindurss@outlook.com
